// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'tr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Home: {
		/**
		 * G​e​n​e​r​a​t​e
		 */
		GenerateButton: string
		PromptInput: {
			/**
			 * P​o​r​t​r​a​i​t​ ​o​f​ ​a​ ​c​a​t​ ​b​y​ ​V​a​n​ ​G​o​g​h
			 */
			Placeholder: string
		}
		WidthTabBar: {
			/**
			 * W​i​d​t​h
			 */
			Title: string
			/**
			 * T​h​e​ ​w​i​d​t​h​ ​o​f​ ​t​h​e​ ​i​m​a​g​e​.
			 */
			Paragraph: string
		}
		HeightTabBar: {
			/**
			 * H​e​i​g​h​t
			 */
			Title: string
			/**
			 * T​h​e​ ​h​e​i​g​h​t​ ​o​f​ ​t​h​e​ ​i​m​a​g​e​.
			 */
			Paragraph: string
		}
		InferenceStepsTabBar: {
			/**
			 * I​n​f​e​r​e​n​c​e​ ​S​t​e​p​s
			 */
			Title: string
			/**
			 * H​o​w​ ​m​a​n​y​ ​s​t​e​p​s​ ​w​i​l​l​ ​b​e​ ​t​a​k​e​n​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​(​d​i​f​f​u​s​e​)​ ​t​h​e​ ​i​m​a​g​e​.
			 */
			Paragraph: string
		}
		GuidanceScaleSlider: {
			/**
			 * G​u​i​d​a​n​c​e​ ​S​c​a​l​e
			 */
			Title: string
			/**
			 * H​o​w​ ​s​i​m​i​l​a​r​ ​t​h​e​ ​i​m​a​g​e​ ​w​i​l​l​ ​b​e​ ​t​o​ ​y​o​u​r​ ​p​r​o​m​p​t​.​ ​H​i​g​h​e​r​ ​v​a​l​u​e​s​ ​m​a​k​e​ ​t​h​e​ ​i​m​a​g​e​ ​c​l​o​s​e​r​ ​t​o​ ​y​o​u​r​ ​p​r​o​m​p​t​.
			 */
			Paragraph: string
		}
		NegativePromptInput: {
			/**
			 * N​e​g​a​t​i​v​e​ ​P​r​o​m​p​t
			 */
			Title: string
			/**
			 * N​e​g​a​t​i​v​e​ ​p​r​o​m​p​t
			 */
			Placeholder: string
			/**
			 * T​o​ ​r​e​m​o​v​e​ ​u​n​w​a​n​t​e​d​ ​t​h​i​n​g​s​ ​f​r​o​m​ ​t​h​e​ ​i​m​a​g​e​.​ ​I​t​ ​d​o​e​s​ ​t​h​e​ ​o​p​p​o​s​i​t​e​ ​o​f​ ​w​h​a​t​ ​t​h​e​ ​p​r​o​m​p​t​ ​d​o​e​s​.
			 */
			Paragraph: string
		}
		SeedInput: {
			/**
			 * S​e​e​d
			 */
			Title: string
			/**
			 * S​e​e​d​ ​n​u​m​b​e​r
			 */
			Placeholder: string
			/**
			 * G​e​t​ ​r​e​p​e​a​t​a​b​l​e​ ​r​e​s​u​l​t​s​.​ ​A​ ​s​e​e​d​ ​c​o​m​b​i​n​e​d​ ​w​i​t​h​ ​t​h​e​ ​s​a​m​e​ ​p​r​o​m​p​t​ ​a​n​d​ ​o​p​t​i​o​n​s​ ​g​e​n​e​r​a​t​e​s​ ​t​h​e​ ​s​a​m​e​ ​i​m​a​g​e​.
			 */
			Paragraph: string
		}
	}
	Navbar: {
		/**
		 * H​o​m​e
		 */
		HomeTab: string
		/**
		 * H​i​s​t​o​r​y
		 */
		HistoryTab: string
		/**
		 * G​a​l​l​e​r​y
		 */
		GalleryTab: string
		/**
		 * L​i​v​e
		 */
		LiveTab: string
	}
	Settings: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		Title: string
		/**
		 * S​w​i​t​c​h​ ​S​e​r​v​e​r
		 */
		SwitchServerButton: string
		/**
		 * S​u​b​m​i​t​ ​t​o​ ​G​a​l​l​e​r​y
		 */
		SubmitToGalleryToggle: string
		/**
		 * A​d​v​a​n​c​e​d​ ​M​o​d​e
		 */
		AdvancedModeToggle: string
		/**
		 * D​a​r​k​ ​M​o​d​e
		 */
		DarkModeToggle: string
	}
	GenerationFullscreen: {
		/**
		 * D​o​w​n​l​o​a​d
		 */
		DownloadButton: string
		/**
		 * C​o​p​y​ ​P​r​o​m​p​t
		 */
		CopyPromptButton: string
		/**
		 * C​o​p​y​ ​N​e​g​a​t​i​v​e​ ​P​r​o​m​p​t
		 */
		CopyNegativePromptButton: string
		/**
		 * R​e​r​o​l​l
		 */
		RerollButton: string
		/**
		 * R​e​g​e​n​e​r​a​t​e
		 */
		RegenerateButton: string
		/**
		 * G​e​n​e​r​a​t​e
		 */
		GenerateButton: string
		/**
		 * U​p​s​c​a​l​e
		 */
		UpscaleButton: string
		UpscaleTabBar: {
			/**
			 * U​p​s​c​a​l​e​d
			 */
			UpscaledTitle: string
			/**
			 * N​o​r​m​a​l
			 */
			OriginalTitle: string
		}
		Dimensions: {
			/**
			 * D​i​m​e​n​s​i​o​n​s
			 */
			Title: string
		}
		Duration: {
			/**
			 * D​u​r​a​t​i​o​n
			 */
			Title: string
		}
	}
}

export type TranslationFunctions = {
	Home: {
		/**
		 * Generate
		 */
		GenerateButton: () => LocalizedString
		PromptInput: {
			/**
			 * Portrait of a cat by Van Gogh
			 */
			Placeholder: () => LocalizedString
		}
		WidthTabBar: {
			/**
			 * Width
			 */
			Title: () => LocalizedString
			/**
			 * The width of the image.
			 */
			Paragraph: () => LocalizedString
		}
		HeightTabBar: {
			/**
			 * Height
			 */
			Title: () => LocalizedString
			/**
			 * The height of the image.
			 */
			Paragraph: () => LocalizedString
		}
		InferenceStepsTabBar: {
			/**
			 * Inference Steps
			 */
			Title: () => LocalizedString
			/**
			 * How many steps will be taken to generate (diffuse) the image.
			 */
			Paragraph: () => LocalizedString
		}
		GuidanceScaleSlider: {
			/**
			 * Guidance Scale
			 */
			Title: () => LocalizedString
			/**
			 * How similar the image will be to your prompt. Higher values make the image closer to your prompt.
			 */
			Paragraph: () => LocalizedString
		}
		NegativePromptInput: {
			/**
			 * Negative Prompt
			 */
			Title: () => LocalizedString
			/**
			 * Negative prompt
			 */
			Placeholder: () => LocalizedString
			/**
			 * To remove unwanted things from the image. It does the opposite of what the prompt does.
			 */
			Paragraph: () => LocalizedString
		}
		SeedInput: {
			/**
			 * Seed
			 */
			Title: () => LocalizedString
			/**
			 * Seed number
			 */
			Placeholder: () => LocalizedString
			/**
			 * Get repeatable results. A seed combined with the same prompt and options generates the same image.
			 */
			Paragraph: () => LocalizedString
		}
	}
	Navbar: {
		/**
		 * Home
		 */
		HomeTab: () => LocalizedString
		/**
		 * History
		 */
		HistoryTab: () => LocalizedString
		/**
		 * Gallery
		 */
		GalleryTab: () => LocalizedString
		/**
		 * Live
		 */
		LiveTab: () => LocalizedString
	}
	Settings: {
		/**
		 * Settings
		 */
		Title: () => LocalizedString
		/**
		 * Switch Server
		 */
		SwitchServerButton: () => LocalizedString
		/**
		 * Submit to Gallery
		 */
		SubmitToGalleryToggle: () => LocalizedString
		/**
		 * Advanced Mode
		 */
		AdvancedModeToggle: () => LocalizedString
		/**
		 * Dark Mode
		 */
		DarkModeToggle: () => LocalizedString
	}
	GenerationFullscreen: {
		/**
		 * Download
		 */
		DownloadButton: () => LocalizedString
		/**
		 * Copy Prompt
		 */
		CopyPromptButton: () => LocalizedString
		/**
		 * Copy Negative Prompt
		 */
		CopyNegativePromptButton: () => LocalizedString
		/**
		 * Reroll
		 */
		RerollButton: () => LocalizedString
		/**
		 * Regenerate
		 */
		RegenerateButton: () => LocalizedString
		/**
		 * Generate
		 */
		GenerateButton: () => LocalizedString
		/**
		 * Upscale
		 */
		UpscaleButton: () => LocalizedString
		UpscaleTabBar: {
			/**
			 * Upscaled
			 */
			UpscaledTitle: () => LocalizedString
			/**
			 * Normal
			 */
			OriginalTitle: () => LocalizedString
		}
		Dimensions: {
			/**
			 * Dimensions
			 */
			Title: () => LocalizedString
		}
		Duration: {
			/**
			 * Duration
			 */
			Title: () => LocalizedString
		}
	}
}

export type Formatters = {}
