// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/yekta/stablecog/go-apps/database/ent/runtime.go

const (
	Version = "v0.11.5"                                         // Version of ent codegen.
	Sum     = "h1:V2qhG91C4PMQTa82Q4StoESMQ4dzkMNeStCzszxi0jQ=" // Sum of ent codegen.
)
