<script lang="ts">
	import { themeApp } from '$ts/stores/theme';
</script>

<section
	id="describe-anything"
	class="w-full lg:h-[calc(100svh-env(safe-area-inset-bottom)-10rem)] lg:min-h-[40rem]
		flex flex-col lg:flex-row items-center justify-between"
>
	<div
		class="flex-1 min-h-0 w-full lg:h-full flex flex-col lg:flex-row
			lg:items-center lg:justify-center justify-start items-center relative"
	>
		<div
			class="w-full h-auto lg:flex-1 lg:h-full relative overflow-hidden flex justify-end lg:pr-0
				order-2 lg:order-1"
		>
			<div
				class="h-full relative pr-[6%] -ml-[6%] md:pr-[6%] md:-ml-[6%] lg:pr-0 lg:ml-0 overflow-hidden flex justify-end"
			>
				<div class="aspect-[5/4] h-full relative">
					<img
						style="
              -webkit-mask-image: url(/landing/cat/cat-mask.svg);
              mask-image: url(/landing/cat/cat-mask.svg);
              -webkit-mask-repeat: no-repeat;
              mask-repeat: no-repeat;
              mask-size: cover;
              -webkit-mask-size: cover;
              mask-position: right center;
              -webkit-mask-position: right center;
            "
						class="w-full h-full"
						srcset="
              /landing/cat/cat-512.webp 512w,
              /landing/cat/cat-768.webp 768w,
              /landing/cat/cat-1024.webp 1024w,
              /landing/cat/cat-1440.webp 1440w,
              /landing/cat/cat-1920.webp 1920w,
            "
						sizes="(min-width: 1024px) 50vw, 100vw"
						src="/landing/cat/cat-1920.webp"
						alt="Cat"
						width="1920"
						height="1536"
					/>
					<img
						class="w-full h-full absolute right-0 top-0"
						src={$themeApp === 'light'
							? '/landing/cat/cat-outline-light.svg'
							: '/landing/cat/cat-outline-dark.svg'}
						alt="Cat Outline"
						width="1920"
						height="1536"
					/>
				</div>
			</div>
			<div
				class="absolute right-0 bottom-[15%] md:bottom-[20%] lg:bottom-[20%] w-full py-2 px-3 md:pl-8 md:pr-12 lg:pl-4 lg:pr-1 flex justify-end"
			>
				<p
					class="px-4 font-semibold py-3 rounded-lg md:rounded-xl bg-c-bg-secondary text-xs md:text-base lg:text-lg lg:px-5 ring-2 ring-c-bg-tertiary shadow-xl shadow-c-shadow/[var(--o-shadow-stronger)]"
				>
					majestic cat, psychedelic, violet tones, fantasy landscape
				</p>
			</div>
		</div>
		<div
			class="px-6 pt-6 pb-8 lg:pt-12 lg:pb-20 lg:w-2/5 xl:w-1/2 order-1 lg:order-2
				lg:pl-10 lg:pr-12 xl:pl-16 flex flex-col items-center lg:items-start"
		>
			<div class="flex flex-col items-center lg:items-start">
				<h2
					class="max-w-[19rem] md:max-w-[22rem] lg:max-w-[28rem] font-bold text-3xl md:text-4xl
						lg:text-5xl flex-1 leading-tight lg:leading-tight text-center lg:text-left"
				>
					Describe anything
				</h2>
				<p
					class="max-w-[22rem] lg:max-w-[28rem] leading-relaxed md:text-lg lg:text-xl mt-2 text-center lg:text-left text-c-on-bg/75"
				>
					Anything you like, in thousands of different styles. It’ll be generated by AI in seconds.
				</p>
			</div>
		</div>
	</div>
</section>
