// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yekta/stablecog/go-apps/database/ent/generationg"
)

// GenerationGCreate is the builder for creating a GenerationG entity.
type GenerationGCreate struct {
	config
	mutation *GenerationGMutation
	hooks    []Hook
}

// Mutation returns the GenerationGMutation object of the builder.
func (gg *GenerationGCreate) Mutation() *GenerationGMutation {
	return gg.mutation
}

// Save creates the GenerationG in the database.
func (gg *GenerationGCreate) Save(ctx context.Context) (*GenerationG, error) {
	return withHooks[*GenerationG, GenerationGMutation](ctx, gg.sqlSave, gg.mutation, gg.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gg *GenerationGCreate) SaveX(ctx context.Context) *GenerationG {
	v, err := gg.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gg *GenerationGCreate) Exec(ctx context.Context) error {
	_, err := gg.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gg *GenerationGCreate) ExecX(ctx context.Context) {
	if err := gg.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gg *GenerationGCreate) check() error {
	return nil
}

func (gg *GenerationGCreate) sqlSave(ctx context.Context) (*GenerationG, error) {
	if err := gg.check(); err != nil {
		return nil, err
	}
	_node, _spec := gg.createSpec()
	if err := sqlgraph.CreateNode(ctx, gg.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gg.mutation.id = &_node.ID
	gg.mutation.done = true
	return _node, nil
}

func (gg *GenerationGCreate) createSpec() (*GenerationG, *sqlgraph.CreateSpec) {
	var (
		_node = &GenerationG{config: gg.config}
		_spec = &sqlgraph.CreateSpec{
			Table: generationg.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: generationg.FieldID,
			},
		}
	)
	return _node, _spec
}

// GenerationGCreateBulk is the builder for creating many GenerationG entities in bulk.
type GenerationGCreateBulk struct {
	config
	builders []*GenerationGCreate
}

// Save creates the GenerationG entities in the database.
func (ggb *GenerationGCreateBulk) Save(ctx context.Context) ([]*GenerationG, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ggb.builders))
	nodes := make([]*GenerationG, len(ggb.builders))
	mutators := make([]Mutator, len(ggb.builders))
	for i := range ggb.builders {
		func(i int, root context.Context) {
			builder := ggb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenerationGMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ggb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ggb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ggb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ggb *GenerationGCreateBulk) SaveX(ctx context.Context) []*GenerationG {
	v, err := ggb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ggb *GenerationGCreateBulk) Exec(ctx context.Context) error {
	_, err := ggb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ggb *GenerationGCreateBulk) ExecX(ctx context.Context) {
	if err := ggb.Exec(ctx); err != nil {
		panic(err)
	}
}
