// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yekta/stablecog/go-apps/database/ent/generationg"
	"github.com/yekta/stablecog/go-apps/database/ent/predicate"
)

// GenerationGDelete is the builder for deleting a GenerationG entity.
type GenerationGDelete struct {
	config
	hooks    []Hook
	mutation *GenerationGMutation
}

// Where appends a list predicates to the GenerationGDelete builder.
func (gg *GenerationGDelete) Where(ps ...predicate.GenerationG) *GenerationGDelete {
	gg.mutation.Where(ps...)
	return gg
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gg *GenerationGDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, GenerationGMutation](ctx, gg.sqlExec, gg.mutation, gg.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gg *GenerationGDelete) ExecX(ctx context.Context) int {
	n, err := gg.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gg *GenerationGDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: generationg.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: generationg.FieldID,
			},
		},
	}
	if ps := gg.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gg.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gg.mutation.done = true
	return affected, err
}

// GenerationGDeleteOne is the builder for deleting a single GenerationG entity.
type GenerationGDeleteOne struct {
	gg *GenerationGDelete
}

// Exec executes the deletion query.
func (ggo *GenerationGDeleteOne) Exec(ctx context.Context) error {
	n, err := ggo.gg.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{generationg.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ggo *GenerationGDeleteOne) ExecX(ctx context.Context) {
	ggo.gg.ExecX(ctx)
}
