// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/yekta/stablecog/go-apps/database/ent/generationg"
)

// GenerationG is the model entity for the GenerationG schema.
type GenerationG struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GenerationG) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case generationg.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type GenerationG", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GenerationG fields.
func (ge *GenerationG) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case generationg.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ge.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this GenerationG.
// Note that you need to call GenerationG.Unwrap() before calling this method if this GenerationG
// was returned from a transaction, and the transaction was committed or rolled back.
func (ge *GenerationG) Update() *GenerationGUpdateOne {
	return (&GenerationGClient{config: ge.config}).UpdateOne(ge)
}

// Unwrap unwraps the GenerationG entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ge *GenerationG) Unwrap() *GenerationG {
	_tx, ok := ge.config.driver.(*txDriver)
	if !ok {
		panic("ent: GenerationG is not a transactional entity")
	}
	ge.config.driver = _tx.drv
	return ge
}

// String implements the fmt.Stringer.
func (ge *GenerationG) String() string {
	var builder strings.Builder
	builder.WriteString("GenerationG(")
	builder.WriteString(fmt.Sprintf("id=%v", ge.ID))
	builder.WriteByte(')')
	return builder.String()
}

// GenerationGs is a parsable slice of GenerationG.
type GenerationGs []*GenerationG

func (ge GenerationGs) config(cfg config) {
	for _i := range ge {
		ge[_i].config = cfg
	}
}
