import {
	PUBLIC_APP_MODE,
	PUBLIC_SUPABASE_ANON_KEY,
	PUBLIC_SUPABASE_ANON_KEY_QA,
	PUBLIC_SUPABASE_URL,
	PUBLIC_SUPABASE_URL_QA
} from '$env/static/public';

export const supabaseUrl =
	(PUBLIC_APP_MODE === 'qa'
		? PUBLIC_SUPABASE_URL_QA
		: PUBLIC_APP_MODE === 'dev'
		? PUBLIC_SUPABASE_URL
		: PUBLIC_SUPABASE_URL) || '';

export const supabaseAnonKey =
	(PUBLIC_APP_MODE === 'qa'
		? PUBLIC_SUPABASE_ANON_KEY_QA
		: PUBLIC_APP_MODE === 'dev'
		? PUBLIC_SUPABASE_ANON_KEY
		: PUBLIC_SUPABASE_ANON_KEY) || '';
